services:
  app_db:
    image: mysql:latest
    container_name: app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootdb@server
      MYSQL_DATABASE: database
      MYSQL_USER: seenit
      MYSQL_PASSWORD: rootdb@server
    ports:
      - 3306:3306
    volumes:
      - mydbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pyour_root_password_change_me"]
      timeout: 20s
      retries: 10
      interval: 30s
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: app_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootdb@server
    ports:
      - 8080:80
    depends_on:
      - app_db


  seen_it_frontend:
    container_name: webui
    build: ./frontEnd 
    ports:
      - "5173:5173"
    volumes:
      - ./frontEnd:/app
      - ./frontEnd/node_modules:/app/node_modules
    environment:
        NODE_ENV: developement
    stdin_open: true
    command: npm start
    depends_on:
      app_db:
        condition: service_healthy # Ensure 'db' service is healthy before starting nodejs_app
    restart: always
  
  seen_it_backend:
    container_name: expressjs_server
    build: ./server
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    environment:
        NODE_ENV: production
        DB_HOST: app_db
        DB_USER: seenit
        DB_PASSWORD: rootdb@server
        DB_NAME: database
        DB_PORT: 3306
        APP_URL: http://localhost:5173
    depends_on:
      - app_db

volumes:
  mydbdata:
