services:
  app_db:
    image: mysql:latest
    container_name: ap_db
    environment:
      MYSQL_ROOT_PASSWORD: rootdb@server
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
    volumes:
      - ./mydbdata:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: pnk_archive_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootdb@server
    ports:
      - 8080:80
    depends_on:
      - app_db

  seen_it_backend:
    container_name: expressjs_server
    build: ./server
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    environment:
        NODE_ENV: production
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASSWORD: rootdb@server
        DB_NAME: database
        DB_PORT: 3306
        APP_URL: http://localhost:5173
    depends_on:
      - app_db
  seen_it_frontend:
    container_name: webui
    build: ./frontEnd 
    ports:
      - "5173:5173"
    volumes:
      - ./frontEnd:/app
      - ./frontEnd/node_modules:/app/node_modules
    environment:
        NODE_ENV: developement
    stdin_open: true
    command: npm start
    depends_on:
      - app_db
      - seen_it_backend
volumes:
  mydbdata:
